require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PayementsController do

  # This should return the minimal set of attributes required to create a valid
  # Payement. As you add validations to Payement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PayementsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all payements as @payements" do
      payement = Payement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:payements).should eq([payement])
    end
  end

  describe "GET show" do
    it "assigns the requested payement as @payement" do
      payement = Payement.create! valid_attributes
      get :show, {:id => payement.to_param}, valid_session
      assigns(:payement).should eq(payement)
    end
  end

  describe "GET new" do
    it "assigns a new payement as @payement" do
      get :new, {}, valid_session
      assigns(:payement).should be_a_new(Payement)
    end
  end

  describe "GET edit" do
    it "assigns the requested payement as @payement" do
      payement = Payement.create! valid_attributes
      get :edit, {:id => payement.to_param}, valid_session
      assigns(:payement).should eq(payement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Payement" do
        expect {
          post :create, {:payement => valid_attributes}, valid_session
        }.to change(Payement, :count).by(1)
      end

      it "assigns a newly created payement as @payement" do
        post :create, {:payement => valid_attributes}, valid_session
        assigns(:payement).should be_a(Payement)
        assigns(:payement).should be_persisted
      end

      it "redirects to the created payement" do
        post :create, {:payement => valid_attributes}, valid_session
        response.should redirect_to(Payement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payement as @payement" do
        # Trigger the behavior that occurs when invalid params are submitted
        Payement.any_instance.stub(:save).and_return(false)
        post :create, {:payement => {}}, valid_session
        assigns(:payement).should be_a_new(Payement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Payement.any_instance.stub(:save).and_return(false)
        post :create, {:payement => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payement" do
        payement = Payement.create! valid_attributes
        # Assuming there are no other payements in the database, this
        # specifies that the Payement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Payement.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => payement.to_param, :payement => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested payement as @payement" do
        payement = Payement.create! valid_attributes
        put :update, {:id => payement.to_param, :payement => valid_attributes}, valid_session
        assigns(:payement).should eq(payement)
      end

      it "redirects to the payement" do
        payement = Payement.create! valid_attributes
        put :update, {:id => payement.to_param, :payement => valid_attributes}, valid_session
        response.should redirect_to(payement)
      end
    end

    describe "with invalid params" do
      it "assigns the payement as @payement" do
        payement = Payement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Payement.any_instance.stub(:save).and_return(false)
        put :update, {:id => payement.to_param, :payement => {}}, valid_session
        assigns(:payement).should eq(payement)
      end

      it "re-renders the 'edit' template" do
        payement = Payement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Payement.any_instance.stub(:save).and_return(false)
        put :update, {:id => payement.to_param, :payement => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payement" do
      payement = Payement.create! valid_attributes
      expect {
        delete :destroy, {:id => payement.to_param}, valid_session
      }.to change(Payement, :count).by(-1)
    end

    it "redirects to the payements list" do
      payement = Payement.create! valid_attributes
      delete :destroy, {:id => payement.to_param}, valid_session
      response.should redirect_to(payements_url)
    end
  end

end
